# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef16e7c30f68a3ef0ab68c8363529fbbf03501192439c8debec254e3f683a3274ae11c2d1492f4e0156c42caad2db54f26a0195c945a6bc945c1ba2c23e641d

test:
  secret_key_base: ab226aad5bbff95cce33e3f96b4fc0c677b97d1ad000db5c04c0bc7fb82119044d1a79deee5af92f962bac24e80c5c100bcb5fa3d8382a0f0b46ff8b4fd42869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
